apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: go
  name: go-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go
  template:
    metadata:
      labels:
        app: go
    spec:
      containers:
      - image: gcr.io/test-capstone-350108/go-test:v0.52
        name: go-test
        ports:
        - containerPort: 8080
